In [2]:
import pandas as pd

In [9]:
df = pd.read_csv("files/placement - placement.csv")

In [10]:
df

    cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]

In [ ]:
# x = df.astype(int)  ## used for type conversion
df['cgpa'] = df['cgpa'].astype(int)

In [8]:
df.head()

   cgpa  resume_score  placed
0     8          6.52       1
1     6          5.17       0
2     8          8.86       1
3     6          7.27       1
4     7          7.30       1

In [12]:
df['resume_score'] = df['resume_score'].astype(int)

In [13]:
df.head(5)

   cgpa  resume_score  placed
0  8.14             6       1
1  6.17             5       0
2  8.27             8       1
3  6.88             7       1
4  7.52             7       1

In [14]:
# to add the value in column 
df['cgpa'] = df['cgpa'].add(10)

In [15]:
df

     cgpa  resume_score  placed
0   18.14             6       1
1   16.17             5       0
2   18.27             8       1
3   16.88             7       1
4   17.52             7       1
..    ...           ...     ...
95  16.33             6       0
96  18.23             7       1
97  16.65             7       0
98  18.14             5       1
99  16.09             6       0

[100 rows x 3 columns]

In [16]:
# mean of the column 
r = df['cgpa'].mean()

In [17]:
r

np.float64(16.942200000000003)

In [18]:
s = df['cgpa'].median()
s

np.float64(16.619999999999997)

In [11]:
# filter in pandas
g  = df.filter(items = ['cgpa','placed'])
g
df[['cgpa' , 'placed']]

    cgpa  placed
0   8.14       1
1   6.17       0
2   8.27       1
3   6.88       1
4   7.52       1
..   ...     ...
95  6.33       0
96  8.23       1
97  6.65       0
98  8.14       1
99  6.09       0

[100 rows x 2 columns]

In [19]:
# axis = 0 --> means row wise operration 
s = df.filter(items = [5,6] , axis = 0)
s

    cgpa  resume_score  placed
5  18.77             6       1
6  15.34             7       0

In [30]:
s = df.to_dict()  # save in dictionary format
s

{'cgpa': {0: 18.14,
  1: 16.17,
  2: 18.27,
  3: 16.88,
  4: 17.52,
  5: 18.77,
  6: 15.34,
  7: 16.56,
  8: 16.32,
  9: 17.69,
  10: 16.18,
  11: 15.440000000000001,
  12: 16.09,
  13: 18.5,
  14: 17.509999999999998,
  15: 18.880000000000003,
  16: 18.04,
  17: 17.81,
  18: 15.940000000000001,
  19: 16.75,
  20: 15.8,
  21: 16.53,
  22: 16.16,
  23: 16.05,
  24: 18.22,
  25: 17.759999999999998,
  26: 16.27,
  27: 15.51,
  28: 17.46,
  29: 16.19,
  30: 17.36,
  31: 15.92,
  32: 15.870000000000001,
  33: 18.43,
  34: 18.869999999999997,
  35: 18.07,
  36: 18.16,
  37: 19.05,
  38: 16.0,
  39: 17.5,
  40: 18.25,
  41: 18.68,
  42: 16.9,
  43: 18.21,
  44: 15.469999999999999,
  45: 18.1,
  46: 15.83,
  47: 17.05,
  48: 15.54,
  49: 15.46,
  50: 18.22,
  51: 16.54,
  52: 15.9,
  53: 16.0,
  54: 15.92,
  55: 16.94,
  56: 16.13,
  57: 16.34,
  58: 16.47,
  59: 15.95,
  60: 15.870000000000001,
  61: 16.89,
  62: 15.75,
  63: 18.65,
  64: 17.93,
  65: 16.04,
  66: 18.35,
  67: 16.59,
  68: 16.009999999999998,
  69: 18.060000000000002,
  70: 17.12,
  71: 17.34,
  72: 17.63,
  73: 15.76,
  74: 15.54,
  75: 16.34,
  76: 19.4,
  77: 15.879999999999999,
  78: 15.79,
  79: 15.27,
  80: 17.83,
  81: 16.12,
  82: 17.92,
  83: 17.6,
  84: 15.76,
  85: 16.72,
  86: 16.18,
  87: 15.620000000000001,
  88: 18.07,
  89: 15.99,
  90: 15.85,
  91: 18.28,
  92: 15.43,
  93: 19.310000000000002,
  94: 18.009999999999998,
  95: 16.33,
  96: 18.23,
  97: 16.65,
  98: 18.14,
  99: 16.09},
 'resume_score': {0: 6.52,
  1: 5.17,
  2: 8.86,
  3: 7.27,
  4: 7.3,
  5: 6.19,
  6: 7.09,
  7: 6.29,
  8: 6.71,
  9: 7.12,
  10: 6.35,
  11: 6.54,
  12: 7.01,
  13: 5.09,
  14: 6.25,
  15: 5.93,
  16: 7.64,
  17: 8.71,
  18: 5.88,
  19: 8.11,
  20: 8.06,
  21: 7.64,
  22: 5.77,
  23: 7.13,
  24: 6.18,
  25: 5.68,
  26: 6.47,
  27: 6.15,
  28: 7.67,
  29: 7.3,
  30: 7.15,
  31: 7.02,
  32: 7.96,
  33: 7.73,
  34: 7.19,
  35: 7.48,
  36: 7.56,
  37: 8.21,
  38: 8.72,
  39: 6.19,
  40: 5.32,
  41: 5.15,
  42: 6.91,
  43: 7.95,
  44: 5.92,
  45: 5.44,
  46: 5.21,
  47: 8.14,
  48: 6.57,
  49: 6.73,
  50: 6.74,
  51: 7.39,
  52: 7.5,
  53: 7.16,
  54: 7.18,
  55: 6.87,
  56: 6.43,
  57: 7.21,
  58: 7.37,
  59: 7.57,
  60: 6.64,
  61: 7.96,
  62: 8.43,
  63: 7.58,
  64: 8.09,
  65: 8.75,
  66: 8.02,
  67: 6.81,
  68: 7.49,
  69: 9.06,
  70: 7.41,
  71: 8.22,
  72: 7.98,
  73: 6.48,
  74: 7.36,
  75: 7.94,
  76: 5.5,
  77: 6.92,
  78: 5.66,
  79: 7.28,
  80: 7.7,
  81: 6.72,
  82: 6.06,
  83: 8.08,
  84: 6.49,
  85: 5.46,
  86: 5.76,
  87: 5.05,
  88: 6.07,
  89: 7.49,
  90: 5.56,
  91: 6.3,
  92: 6.18,
  93: 7.39,
  94: 4.95,
  95: 6.38,
  96: 7.76,
  97: 7.78,
  98: 5.63,
  99: 6.61},
 'placed': {0: 1,
  1: 0,
  2: 1,
  3: 1,
  4: 1,
  5: 1,
  6: 0,
  7: 0,
  8: 0,
  9: 1,
  10: 0,
  11: 0,
  12: 0,
  13: 1,
  14: 1,
  15: 1,
  16: 1,
  17: 1,
  18: 0,
  19: 1,
  20: 0,
  21: 0,
  22: 0,
  23: 0,
  24: 1,
  25: 1,
  26: 0,
  27: 0,
  28: 1,
  29: 0,
  30: 1,
  31: 0,
  32: 0,
  33: 1,
  34: 1,
  35: 1,
  36: 1,
  37: 1,
  38: 0,
  39: 1,
  40: 1,
  41: 1,
  42: 1,
  43: 1,
  44: 0,
  45: 1,
  46: 0,
  47: 1,
  48: 0,
  49: 0,
  50: 1,
  51: 0,
  52: 0,
  53: 0,
  54: 0,
  55: 1,
  56: 0,
  57: 0,
  58: 0,
  59: 0,
  60: 0,
  61: 1,
  62: 0,
  63: 1,
  64: 1,
  65: 0,
  66: 1,
  67: 1,
  68: 0,
  69: 1,
  70: 1,
  71: 1,
  72: 1,
  73: 0,
  74: 0,
  75: 1,
  76: 1,
  77: 0,
  78: 0,
  79: 0,
  80: 1,
  81: 0,
  82: 1,
  83: 1,
  84: 0,
  85: 0,
  86: 0,
  87: 0,
  88: 1,
  89: 0,
  90: 0,
  91: 1,
  92: 0,
  93: 1,
  94: 1,
  95: 0,
  96: 1,
  97: 0,
  98: 1,
  99: 0}}

In [ ]:
q = df.to_string()  # save in string format

In [33]:
idx = df.columns 
idx

Index(['cgpa', 'resume_score', 'placed'], dtype='object')

In [34]:
label = df.columns[0]  #first column label
label

'cgpa'

In [36]:
p = df.columns.tolist()  # list of column labels 
p

['cgpa', 'resume_score', 'placed']

In [37]:
# reaname a coloumn 
p = df.rename(columns={'cgpa': 'updated_cgpa', 'resume_score' : 'semester_marks'})
p

    updated_cgpa  semester_marks  placed
0           8.14            6.52       1
1           6.17            5.17       0
2           8.27            8.86       1
3           6.88            7.27       1
4           7.52            7.30       1
..           ...             ...     ...
95          6.33            6.38       0
96          8.23            7.76       1
97          6.65            7.78       0
98          8.14            5.63       1
99          6.09            6.61       0

[100 rows x 3 columns]

In [38]:
df['half'] = df['cgpa'].where(df['cgpa']>7 , other = 0)
df.head(5)

   cgpa  resume_score  placed  half
0  8.14          6.52       1  8.14
1  6.17          5.17       0  0.00
2  8.27          8.86       1  8.27
3  6.88          7.27       1  0.00
4  7.52          7.30       1  7.52

In [39]:
df = pd.read_csv("tips - tips.csv")

In [40]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [45]:
p = df.iloc[11:14]
p

    total_bill   tip     sex smoker  day    time  size
11       35.26  5.00  Female     No  Sun  Dinner     4
12       15.42  1.57    Male     No  Sun  Dinner     2
13       18.43  3.00    Male     No  Sun  Dinner     4

In [48]:
p = df.iloc[:,[2]]
p

        sex
0    Female
1      Male
2      Male
3      Male
4    Female
..      ...
239    Male
240  Female
241    Male
242    Male
243  Female

[244 rows x 1 columns]

In [49]:
p = df.rename(columns={'total_bill': 'bill', 'sex' : 'gender'})
p

      bill   tip  gender smoker   day    time  size
0    16.99  1.01  Female     No   Sun  Dinner     2
1    10.34  1.66    Male     No   Sun  Dinner     3
2    21.01  3.50    Male     No   Sun  Dinner     3
3    23.68  3.31    Male     No   Sun  Dinner     2
4    24.59  3.61  Female     No   Sun  Dinner     4
..     ...   ...     ...    ...   ...     ...   ...
239  29.03  5.92    Male     No   Sat  Dinner     3
240  27.18  2.00  Female    Yes   Sat  Dinner     2
241  22.67  2.00    Male    Yes   Sat  Dinner     2
242  17.82  1.75    Male     No   Sat  Dinner     2
243  18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [56]:
df['Male_customer'] = df['sex'].where(df['sex']=='Male' , other = 0)
df

     total_bill   tip     sex smoker   day    time  size Male_customer
0            16  1.01  Female     No   Sun  Dinner     2             0
1            10  1.66    Male     No   Sun  Dinner     3          Male
2            21  3.50    Male     No   Sun  Dinner     3          Male
3            23  3.31    Male     No   Sun  Dinner     2          Male
4            24  3.61  Female     No   Sun  Dinner     4             0
..          ...   ...     ...    ...   ...     ...   ...           ...
239          29  5.92    Male     No   Sat  Dinner     3          Male
240          27  2.00  Female    Yes   Sat  Dinner     2             0
241          22  2.00    Male    Yes   Sat  Dinner     2          Male
242          17  1.75    Male     No   Sat  Dinner     2          Male
243          18  3.00  Female     No  Thur  Dinner     2             0

[244 rows x 8 columns]

In [55]:
df['total_bill'] = df['total_bill'].astype(int)
df

     total_bill   tip     sex smoker   day    time  size Male_customer
0            16  1.01  Female     No   Sun  Dinner     2             0
1            10  1.66    Male     No   Sun  Dinner     3          Male
2            21  3.50    Male     No   Sun  Dinner     3          Male
3            23  3.31    Male     No   Sun  Dinner     2          Male
4            24  3.61  Female     No   Sun  Dinner     4             0
..          ...   ...     ...    ...   ...     ...   ...           ...
239          29  5.92    Male     No   Sat  Dinner     3          Male
240          27  2.00  Female    Yes   Sat  Dinner     2             0
241          22  2.00    Male    Yes   Sat  Dinner     2          Male
242          17  1.75    Male     No   Sat  Dinner     2          Male
243          18  3.00  Female     No  Thur  Dinner     2             0

[244 rows x 8 columns]

In [57]:
df.dtypes

total_bill         int64
tip              float64
sex               object
smoker            object
day               object
time              object
size               int64
Male_customer     object
dtype: object

In [61]:
a = df.head(6)
a

   total_bill   tip     sex smoker  day    time  size Male_customer
0          16  1.01  Female     No  Sun  Dinner     2             0
1          10  1.66    Male     No  Sun  Dinner     3          Male
2          21  3.50    Male     No  Sun  Dinner     3          Male
3          23  3.31    Male     No  Sun  Dinner     2          Male
4          24  3.61  Female     No  Sun  Dinner     4             0
5          25  4.71    Male     No  Sun  Dinner     4          Male

In [63]:
a.to_csv("new_data.csv")

In [64]:
a.to_excel("new_data1.xlsx")

In [65]:
df = pd.read_csv("new_data.csv")
df

,Unnamed: 0,total_bill,tip,sex,smoker,day,time,size,Male_customer
0,0,16,1.01,Female,No,Sun,Dinner,2,0
1,1,10,1.66,Male,No,Sun,Dinner,3,Male
2,2,21,3.50,Male,No,Sun,Dinner,3,Male
3,3,23,3.31,Male,No,Sun,Dinner,2,Male
4,4,24,3.61,Female,No,Sun,Dinner,4,0
5,5,25,4.71,Male,No,Sun,Dinner,4,Male

In [ ]:
# data -->
# numerical --> continuous data --> we can devide furthur.
# salary = 20500.60, weight = 70.54, distance(jaipur to delhi)= 270.78km, height, age 
# categorical --. Descreate data --> we cannot devide further. 
# gender(m,f), marritial status(mu), number of employees in an office,

# covid data --> has_covid(y,n) --> map --> (1,0)
# customer cafe --> bill pay --> 453.25 rupees