In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../files/churn_modelling - churn_modelling.csv')

In [3]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
# Lebel encoding::::

In [5]:
df = df.dropna()

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
lb = LabelEncoder()

In [8]:
df['CustomerId'] = lb.fit_transform(df['CustomerId'])
df['Surname'] = lb.fit_transform(df['Surname'])
df['Geography'] = lb.fit_transform(df['Geography'])
df['Gender'] = lb.fit_transform(df['Gender'])

In [9]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,2736,1115,619,0,0,42,2,0.00,1,1,1,101348.88,1
1,2,3258,1177,608,2,0,41,1,83807.86,1,0,1,112542.58,0
2,3,2104,2040,502,0,0,42,8,159660.80,3,1,0,113931.57,1
3,4,5435,289,699,0,0,39,1,0.00,2,0,0,93826.63,0
4,5,6899,1822,850,2,0,43,2,125510.82,1,1,1,79084.10,0

In [10]:
# Ordinal encoding::::

In [20]:
df = pd.read_csv('../files/churn_modelling - churn_modelling.csv')

In [21]:
df =df.dropna()

In [22]:
from sklearn.preprocessing import OrdinalEncoder

In [23]:
df = df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [24]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [25]:
oe = OrdinalEncoder(categories=[['France', 'Spain', 'Germany'],['Male','Female']])

In [28]:
oe_ar = oe.fit_transform(df[['Geography','Gender']])

In [30]:
new_df = pd.DataFrame(oe_ar, columns = ['Geography', 'Gender'])

In [31]:
new_df.head()

   Geography  Gender
0        0.0     1.0
1        1.0     1.0
2        0.0     1.0
3        0.0     1.0
4        1.0     1.0

In [32]:
# One hot encoding::::

In [33]:
from sklearn.preprocessing import OneHotEncoder

In [35]:
ohe = OneHotEncoder(drop='first', sparse_output=False, dtype=np.int32)

In [36]:
ohe.fit_transform(df[['Geography','Gender']])

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       ...,
       [0, 0, 0],
       [1, 0, 1],
       [0, 0, 0]], shape=(10000, 3), dtype=int32)

In [37]:
# Encoding :::: getdummies

In [38]:
a = pd.get_dummies(df,columns=['Geography','Gender'])

In [39]:
a = a.astype(int)

In [40]:
a

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0,1,1,1,101348,1,1,0,0,1,0
1,608,41,1,83807,1,0,1,112542,0,0,0,1,1,0
2,502,42,8,159660,3,1,0,113931,1,1,0,0,1,0
3,699,39,1,0,2,0,0,93826,0,1,0,0,1,0
4,850,43,2,125510,1,1,1,79084,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0,2,1,0,96270,0,1,0,0,0,1
9996,516,35,10,57369,1,1,1,101699,0,1,0,0,0,1
9997,709,36,7,0,1,0,1,42085,1,1,0,0,1,0
9998,772,42,3,75075,2,1,0,92888,1,0,1,0,0,1
9999,792,28,4,130142,1,1,0,38190,0,1,0,0,1,0

In [41]:
b = pd.get_dummies(df,columns=['Geography','Gender'], drop_first=True)

In [42]:
b = b.astype(int)

In [43]:
b

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0,1,1,1,101348,1,0,0,0
1,608,41,1,83807,1,0,1,112542,0,0,1,0
2,502,42,8,159660,3,1,0,113931,1,0,0,0
3,699,39,1,0,2,0,0,93826,0,0,0,0
4,850,43,2,125510,1,1,1,79084,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0,2,1,0,96270,0,0,0,1
9996,516,35,10,57369,1,1,1,101699,0,0,0,1
9997,709,36,7,0,1,0,1,42085,1,0,0,0
9998,772,42,3,75075,2,1,0,92888,1,1,0,1
9999,792,28,4,130142,1,1,0,38190,0,0,0,0

In [57]:
# standardization

In [48]:
x = b.drop(columns = ['Exited'])
y = b['Exited']

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
x_test, x_train, y_test, y_train = train_test_split(x,y,test_size = 0.2, random_state = 42)

In [51]:
np.round(x_train.describe(),2)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
count,2000.00,2000.00,2000.00,2000.00,2000.00,2000.00,2000.00,2000.00,2000.00,2000.00,2000.00
mean,646.05,39.02,5.05,78020.56,1.53,0.71,0.52,98725.55,0.25,0.24,0.55
std,97.69,10.36,2.93,62134.00,0.59,0.45,0.50,57470.91,0.43,0.43,0.50
min,350.00,18.00,0.00,0.00,1.00,0.00,0.00,11.00,0.00,0.00,0.00
25%,578.00,32.00,2.00,0.00,1.00,0.00,0.00,49711.50,0.00,0.00,0.00
50%,646.50,38.00,5.00,99796.00,1.00,1.00,1.00,98511.50,0.00,0.00,1.00
75%,712.25,44.00,8.00,127871.75,2.00,1.00,1.00,147316.75,0.00,0.00,1.00
max,850.00,92.00,10.00,216109.00,4.00,1.00,1.00,199992.00,1.00,1.00,1.00

In [53]:
from sklearn.preprocessing import StandardScaler

In [54]:
sc = StandardScaler()

In [55]:
x_train_sc = sc.fit_transform(x_train)
x_train_new = pd.DataFrame(x_train_sc, columns = x_train.columns)

In [56]:
np.round(x_train_new.describe(),2)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
count,2000.00,2000.00,2000.00,2000.00,2000.00,2000.00,2000.00,2000.00,2000.00,2000.00,2000.00
mean,0.00,-0.00,0.00,-0.00,-0.00,0.00,0.00,0.00,-0.00,0.00,-0.00
std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
min,-3.03,-2.03,-1.72,-1.26,-0.89,-1.58,-1.05,-1.72,-0.58,-0.56,-1.10
25%,-0.70,-0.68,-1.04,-1.26,-0.89,-1.58,-1.05,-0.85,-0.58,-0.56,-1.10
50%,0.00,-0.10,-0.02,0.35,-0.89,0.63,0.95,-0.00,-0.58,-0.56,0.91
75%,0.68,0.48,1.01,0.80,0.81,0.63,0.95,0.85,-0.58,-0.56,0.91
max,2.09,5.11,1.69,2.22,4.20,0.63,0.95,1.76,1.74,1.77,0.91