In [1]:
# encoding -- get_dummies
# column --> has_covid['yes', 'no'] ----> when we apply get_dummies, we will have two columns: has_covid_yes and has_covid_no
# we can drop one of the columns to avoid multicollinearity, for example, we can drop has_covid_no, and keep has_covid_yes, which will indicate whether the person has covid or not.

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('../files/insurance - insurance.csv')

In [4]:
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [6]:
a = pd.get_dummies(df,columns=['sex', 'smoker', 'region'])

In [7]:
a = a.astype(int)

In [8]:
a

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27,0,16884,1,0,0,1,0,0,0,1
1,18,33,1,1725,0,1,1,0,0,0,1,0
2,28,33,3,4449,0,1,1,0,0,0,1,0
3,33,22,0,21984,0,1,1,0,0,1,0,0
4,32,28,0,3866,0,1,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1333,50,30,3,10600,0,1,1,0,0,1,0,0
1334,18,31,0,2205,1,0,1,0,1,0,0,0
1335,18,36,0,1629,1,0,1,0,0,0,1,0
1336,21,25,0,2007,1,0,1,0,0,0,0,1
1337,61,29,0,29141,1,0,0,1,0,1,0,0

In [9]:
# if i have multiple sub-categories --> 1 column drop --> data multicollinearity 
# --> we can drop one column to avoid multicollinearity, for example, we can drop has_covid_no, and keep has_covid_yes,
#  which will indicate whether the person has covid or not.

# model --> overfitting

In [10]:
b = pd.get_dummies(df,columns = ['sex', 'smoker', 'region'], drop_first=True)

In [11]:
b = b.astype(int)

In [12]:
b

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27,0,16884,0,1,0,0,1
1,18,33,1,1725,1,0,0,1,0
2,28,33,3,4449,1,0,0,1,0
3,33,22,0,21984,1,0,1,0,0
4,32,28,0,3866,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...
1333,50,30,3,10600,1,0,1,0,0
1334,18,31,0,2205,0,0,0,0,0
1335,18,36,0,1629,0,0,0,1,0
1336,21,25,0,2007,0,0,0,0,1
1337,61,29,0,29141,0,1,1,0,0

In [13]:
df = pd.read_csv('../files/covid_toy - covid_toy.csv')

In [15]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [35]:
df = df.dropna()

In [36]:
c = pd.get_dummies(df,columns=['gender','cough','has_covid','city'])

In [37]:
c

,age,fever,gender_Female,gender_Male,cough_Mild,cough_Strong,has_covid_No,has_covid_Yes,city_Bangalore,city_Delhi,city_Kolkata,city_Mumbai
0,60,103.0,False,True,True,False,True,False,False,False,True,False
1,27,100.0,False,True,True,False,False,True,False,True,False,False
2,42,101.0,False,True,True,False,True,False,False,True,False,False
3,31,98.0,True,False,True,False,True,False,False,False,True,False
4,65,101.0,True,False,True,False,True,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
95,12,104.0,True,False,True,False,True,False,True,False,False,False
96,51,101.0,True,False,False,True,False,True,False,False,True,False
97,20,101.0,True,False,True,False,True,False,True,False,False,False
98,5,98.0,True,False,False,True,True,False,False,False,False,True
99,10,98.0,True,False,False,True,False,True,False,False,True,False

In [38]:
c = c.astype(int)

In [39]:
c

,age,fever,gender_Female,gender_Male,cough_Mild,cough_Strong,has_covid_No,has_covid_Yes,city_Bangalore,city_Delhi,city_Kolkata,city_Mumbai
0,60,103,0,1,1,0,1,0,0,0,1,0
1,27,100,0,1,1,0,0,1,0,1,0,0
2,42,101,0,1,1,0,1,0,0,1,0,0
3,31,98,1,0,1,0,1,0,0,0,1,0
4,65,101,1,0,1,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
95,12,104,1,0,1,0,1,0,1,0,0,0
96,51,101,1,0,0,1,0,1,0,0,1,0
97,20,101,1,0,1,0,1,0,1,0,0,0
98,5,98,1,0,0,1,1,0,0,0,0,1
99,10,98,1,0,0,1,0,1,0,0,1,0

In [40]:
d = pd.get_dummies(df,columns=['gender','cough','has_covid','city'], drop_first=True)

In [41]:
d = d.astype(int)

In [42]:
d

,age,fever,gender_Male,cough_Strong,has_covid_Yes,city_Delhi,city_Kolkata,city_Mumbai
0,60,103,1,0,0,0,1,0
1,27,100,1,0,1,1,0,0
2,42,101,1,0,0,1,0,0
3,31,98,0,0,0,0,1,0
4,65,101,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...
95,12,104,0,0,0,0,0,0
96,51,101,0,1,1,0,1,0
97,20,101,0,0,0,0,0,0
98,5,98,0,1,0,0,0,1
99,10,98,0,1,1,0,1,0

In [43]:
# Encoding :::: OneHotEncoding

In [44]:
from sklearn.preprocessing import OneHotEncoder

In [45]:
ohe = OneHotEncoder(drop='first', sparse_output=False, dtype=np.int32)

In [46]:
ohe.fit_transform(df[['gender', 'cough', 'has_covid', 'city']])

array([[1, 0, 0, 0, 1, 0],
       [1, 0, 1, 1, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 1],
       [0, 1, 0, 0, 1, 0],
       [1, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 1, 0],
       [0, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [1, 1, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0],
       [0, 1, 1, 0, 1, 0],
       [0, 0, 1, 1, 0, 0],
       [0, 1, 0, 0, 1, 0],
       [0, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 0],
       [1, 0, 1, 1, 0, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [1, 0, 1, 0, 0, 1],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0],
       [1, 0, 1, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [1, 1, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 0, 0],
       [0, 1, 1, 0, 1, 0],
       [0, 1, 1, 0, 0, 0],
       [1, 0, 1, 1, 0, 0],
       [0, 0, 1, 0, 0, 1],
       [0, 0, 1, 0, 0, 1],
       [0, 1, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 1],
       [0, 0, 1, 0, 1, 0],
       [0, 1, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 1],
       [0, 1, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [1, 1, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 0],
       [1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [1, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 1, 0],
       [0, 0, 1, 0, 0, 1],
       [1, 0, 0, 1, 0, 0],
       [1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 0],
       [1, 0, 1, 0, 0, 0],
       [1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [1, 1, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 1, 0, 0, 1, 0],
       [1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 1],
       [0, 1, 1, 0, 1, 0]], dtype=int32)