In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer 
from sklearn.preprocessing import OneHotEncoder 
from sklearn.preprocessing import OrdinalEncoder

In [9]:
df = pd.read_csv('../files/insurance - insurance.csv')

In [6]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [8]:
from sklearn.model_selection import train_test_split

In [10]:
x_train, x_test, y_train, y_test = train_test_split(df.drop(columns = ['smoker']), df['smoker'], test_size = 0.2, random_state = 42)

In [11]:
x_train

      age     sex     bmi  children     region      charges
560    46  female  19.950         2  northwest   9193.83850
1285   47  female  24.320         0  northeast   8534.67180
1142   52  female  24.860         0  southeast  27117.99378
969    39  female  34.320         5  southeast   8596.82780
486    54  female  21.470         3  northwest  12475.35130
...   ...     ...     ...       ...        ...          ...
1095   18  female  31.350         4  northeast   4561.18850
1130   39  female  23.870         5  southeast   8582.30230
1294   58    male  25.175         0  northeast  11931.12525
860    37  female  47.600         2  southwest  46113.51100
1126   55    male  29.900         0  southwest  10214.63600

[1070 rows x 6 columns]

In [12]:
from sklearn.compose import ColumnTransformer

In [13]:
transformer = ColumnTransformer(transformers = [
    ('tnf1', SimpleImputer(), ['bmi']),
    ('tnf2', OrdinalEncoder(categories=[['female', 'male']]),['sex']),
    ('tnf3', OneHotEncoder(sparse_output = False , drop = 'first'),['region'])
],remainder = 'passthrough')

In [14]:
transformer.fit_transform(x_train).shape

(1070, 8)