In [1]:
# Ordinal Encoding --->
# Label Encoding ---> column[sub1,syub2,sub3...subn] ---> encode
# Ordinal Encoding ---> column[sub1,sub2,...subn] ---> Re-Arrange ---> encode

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("../files/covid_toy - covid_toy.csv")
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [4]:
df = df.dropna()

In [5]:
df = df.drop(columns = ['city', 'age', 'fever'])

In [6]:
df.head(2)

  gender cough has_covid
0   Male  Mild        No
1   Male  Mild       Yes

In [7]:
from sklearn.preprocessing import OrdinalEncoder

In [8]:
oe = OrdinalEncoder(categories=[['Male','Female'],['Mild','Strong'],['No','Yes']])

In [9]:
oe_ar = oe.fit_transform(df)

In [10]:
new_df = pd.DataFrame(oe_ar, columns = df.columns)

In [11]:
new_df

    gender  cough  has_covid
0      0.0    0.0        0.0
1      0.0    0.0        1.0
2      0.0    0.0        0.0
3      1.0    0.0        0.0
4      1.0    0.0        0.0
..     ...    ...        ...
85     1.0    0.0        0.0
86     1.0    1.0        1.0
87     1.0    0.0        0.0
88     1.0    1.0        0.0
89     1.0    1.0        1.0

[90 rows x 3 columns]

In [20]:
# Second Way :::::

In [3]:
df = pd.read_csv("../files/covid_toy - covid_toy.csv")
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [4]:
df = df.dropna()

In [5]:
df = df.drop(columns = ['age','fever','city'])

In [6]:
df.head(3)

  gender cough has_covid
0   Male  Mild        No
1   Male  Mild       Yes
2   Male  Mild        No

In [7]:
x = df.drop(columns = ['has_covid'])
y = df['has_covid']

In [8]:
 x.head(2)

  gender cough
0   Male  Mild
1   Male  Mild

In [9]:
from sklearn.preprocessing import OrdinalEncoder

In [10]:
oe = OrdinalEncoder(categories=[['Male','Female'],['Mild','Strong']])

In [11]:
oe_ar_in = oe.fit_transform(x)

In [12]:
y.head(2)

0     No
1    Yes
Name: has_covid, dtype: object

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
lb = LabelEncoder()

In [15]:
y = lb.fit_transform(y)

In [16]:
y

array([0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1])

In [38]:
# LabelEncoder ---> when we have single column . we cannot set sub-category form .
# has_covid['yes','no'] ---> labelecoder --> [1,0]
# OrdinalEncoder ---> when we have multiple columns .we can set sub-category form.
# has_covid['yes','no'] ---> ord. encoder ---> [0,1]

In [45]:
# first approach ::::
# df ---> categorical column ---> ordinal encoder ---> data transform
# second approach ::::
# df ---> x,y --->
# x ---> encode by Ordinal Encoder
# y ---> encode by Label Encoder

In [ ]:
# tips data --->
# target column 'total_bill'
# Numerical columns ---> remove
# Categorical column ---> OrdinalEncoder

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("../files/tips - tips.csv")

In [3]:
df.head(2)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [12]:
df = df.drop(columns = ['day'])

In [13]:
df

     total_bill   tip     sex smoker    time  size
0         16.99  1.01  Female     No  Dinner     2
1         10.34  1.66    Male     No  Dinner     3
2         21.01  3.50    Male     No  Dinner     3
3         23.68  3.31    Male     No  Dinner     2
4         24.59  3.61  Female     No  Dinner     4
..          ...   ...     ...    ...     ...   ...
239       29.03  5.92    Male     No  Dinner     3
240       27.18  2.00  Female    Yes  Dinner     2
241       22.67  2.00    Male    Yes  Dinner     2
242       17.82  1.75    Male     No  Dinner     2
243       18.78  3.00  Female     No  Dinner     2

[244 rows x 6 columns]

In [14]:
x = df.drop(columns = ['total_bill'])
y = df['total_bill']

In [15]:
from sklearn.preprocessing import OrdinalEncoder

In [16]:
oe = OrdinalEncoder(categories=[['Female','Male'],['Lunch','Dinner']])

In [17]:
oe

OrdinalEncoder(categories=[['Female', 'Male'], ['Lunch', 'Dinner']])

In [ ]:
or_in_