In [ ]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer 
from sklearn.preprocessing import OneHotEncoder 
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv('../files/tips - tips.csv')

In [4]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [7]:

from sklearn.model_selection import train_test_split

In [8]:
x_train,x_test,y_train,y_test = train_test_split(df.drop(columns = 'tip'),df['tip'],test_size=0.2,random_state=42)

In [9]:
x_train

     total_bill     sex smoker   day    time  size
228       13.28    Male     No   Sat  Dinner     2
208       24.27    Male    Yes   Sat  Dinner     2
96        27.28    Male    Yes   Fri  Dinner     2
167       31.71    Male     No   Sun  Dinner     4
84        15.98    Male     No  Thur   Lunch     2
..          ...     ...    ...   ...     ...   ...
106       20.49    Male    Yes   Sat  Dinner     2
14        14.83  Female     No   Sun  Dinner     2
92         5.75  Female    Yes   Fri  Dinner     2
179       34.63    Male    Yes   Sun  Dinner     2
102       44.30  Female    Yes   Sat  Dinner     3

[195 rows x 6 columns]

In [10]:
from sklearn.compose import ColumnTransformer

In [16]:
transformer = ColumnTransformer(transformers = [
    ('t1', SimpleImputer(), ['total_bill']),
    ('t2', OneHotEncoder(sparse_output=False, drop='first'), ['sex']),
    ('t3', OrdinalEncoder(categories=[['Lunch', 'Dinner']]), ['time'])
], remainder='passthrough')

In [17]:
transformer.fit_transform(x_train).shape

(195, 6)