In [1]:
! pip install plotly

Requirement already satisfied: plotly in c:\users\sudhir faujdar\appdata\local\programs\python\python312\lib\site-packages (6.2.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\sudhir faujdar\appdata\local\programs\python\python312\lib\site-packages (from plotly) (1.46.0)
Requirement already satisfied: packaging in c:\users\sudhir faujdar\appdata\local\programs\python\python312\lib\site-packages (from plotly) (25.0)

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import plotly.graph_objects as go 
import plotly.io as pio
pio.templates.default = "plotly_white"

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('c:\\Users\\SUDHIR FAUJDAR\\Desktop\\Adv python\\EDA-Data-Analysis\\files\\Attrition - Attrition.csv')

In [10]:
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [16]:
print(df.isnull().sum())

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [28]:
# check the percentage 
attr_df = df[df['Attrition'] == 'Yes']

In [29]:
attr_df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
14,28,Yes,Travel_Rarely,103,Research & Development,24,3,Life Sciences,1,19,...,2,80,0,6,4,3,4,2,0,3
21,36,Yes,Travel_Rarely,1218,Sales,9,4,Life Sciences,1,27,...,2,80,0,10,4,3,5,3,0,3
24,34,Yes,Travel_Rarely,699,Research & Development,6,1,Medical,1,31,...,3,80,0,8,2,3,4,2,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1438,23,Yes,Travel_Frequently,638,Sales,9,3,Marketing,1,2023,...,1,80,1,1,3,2,1,0,1,0
1442,29,Yes,Travel_Rarely,1092,Research & Development,1,4,Medical,1,2027,...,2,80,3,4,3,4,2,2,2,2
1444,56,Yes,Travel_Rarely,310,Research & Development,7,2,Technical Degree,1,2032,...,4,80,1,14,4,1,10,9,9,8
1452,50,Yes,Travel_Frequently,878,Sales,1,4,Life Sciences,1,2044,...,4,80,2,12,3,3,6,3,0,1
1461,50,Yes,Travel_Rarely,410,Sales,28,3,Marketing,1,2055,...,2,80,1,20,3,3,3,2,2,0

In [30]:
attrition_by_dpt = attr_df.groupby(['Department']).size().reset_index(name = "count")

In [31]:
attrition_by_dpt

               Department  count
0         Human Resources     12
1  Research & Development    133
2                   Sales     92

In [32]:
# create a donut chart
fig = go.Figure(data=[go.Pie(
    labels = attrition_by_dpt['Department'],
    values = attrition_by_dpt['count'],
    hole = 0.4,
    marker = dict(colors=['red' , 'green']),
    textposition = 'inside'
)])

In [ ]:
# upadate the layout
fig.update_layout(title = 'Attrition by Department')
# show the chart
fig.show()

In [34]:
attrition_by_edf = attr_df.groupby(['EducationField']).size().reset_index(name = "count")

In [35]:
attrition_by_edf

     EducationField  count
0   Human Resources      7
1     Life Sciences     89
2         Marketing     35
3           Medical     63
4             Other     11
5  Technical Degree     32

In [36]:
fig = go.Figure(data=[go.Pie(
    labels = attrition_by_edf['EducationField'],
    values = attrition_by_edf['count'],
    hole = 0.4,
    marker = dict(colors=['red' , 'green']),
    textposition = 'inside'
)])

In [38]:
fig.update_layout(title = 'Attrition by Education Field')

fig.show()