In [1]:
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects  as go
pio.templates.default = "plotly_white"

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../files/supply_chain - supply_chain.csv")

In [4]:
df

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,SKU2,11.319683,34,8,9577.749626,Unknown,1,10,88,...,Mumbai,12,971,27,30.688019,Pending,4.580593,Air,Route C,141.920282
3,skincare,SKU3,61.163343,68,83,7766.836426,Non-binary,23,13,59,...,Kolkata,24,937,18,35.624741,Fail,4.746649,Rail,Route A,254.776159
4,skincare,SKU4,4.805496,26,871,2686.505152,Non-binary,5,3,56,...,Delhi,5,414,3,92.065161,Fail,3.145580,Air,Route A,923.440632
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,haircare,SKU95,77.903927,65,672,7386.363944,Unknown,15,14,26,...,Mumbai,18,450,26,58.890686,Pending,1.210882,Air,Route A,778.864241
96,cosmetics,SKU96,24.423131,29,324,7698.424766,Non-binary,67,2,32,...,Mumbai,28,648,28,17.803756,Pending,3.872048,Road,Route A,188.742141
97,haircare,SKU97,3.526111,56,62,4370.916580,Male,46,19,4,...,Mumbai,10,535,13,65.765156,Fail,3.376238,Road,Route A,540.132423
98,skincare,SKU98,19.754605,43,913,8525.952560,Female,53,1,27,...,Chennai,28,581,9,5.604691,Pending,2.908122,Rail,Route A,882.198864
99,haircare,SKU99,68.517833,17,627,9185.185829,Unknown,55,8,59,...,Chennai,29,921,2,38.072899,Fail,0.346027,Rail,Route B,210.743009

In [5]:
df.describe()

,Price,Availability,Number of products sold,Revenue generated,Stock levels,Lead times,Order quantities,Shipping times,Shipping costs,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Defect rates,Costs
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000
mean,49.462461,48.400000,460.990000,5776.048187,47.770000,15.960000,49.220000,5.750000,5.548149,17.080000,567.840000,14.77000,47.266693,2.277158,529.245782
std,31.168193,30.743317,303.780074,2732.841744,31.369372,8.785801,26.784429,2.724283,2.651376,8.846251,263.046861,8.91243,28.982841,1.461366,258.301696
min,1.699976,1.000000,8.000000,1061.618523,0.000000,1.000000,1.000000,1.000000,1.013487,1.000000,104.000000,1.00000,1.085069,0.018608,103.916248
25%,19.597823,22.750000,184.250000,2812.847151,16.750000,8.000000,26.000000,3.750000,3.540248,10.000000,352.000000,7.00000,22.983299,1.009650,318.778455
50%,51.239830,43.500000,392.500000,6006.352023,47.500000,17.000000,52.000000,6.000000,5.320534,18.000000,568.500000,14.00000,45.905622,2.141863,520.430444
75%,77.198228,75.000000,704.250000,8253.976920,73.000000,24.000000,71.250000,8.000000,7.601695,25.000000,797.000000,23.00000,68.621026,3.563995,763.078231
max,99.171329,100.000000,996.000000,9866.465458,100.000000,30.000000,96.000000,10.000000,9.929816,30.000000,985.000000,30.00000,99.466109,4.939255,997.413450

now lets get started with analyzing the supply chain by looking at the relationship between the price of the products and the revenue generated by them:

In [6]:
! pip install statsmodels

Requirement already satisfied: statsmodels in c:\users\sudhir faujdar\appdata\local\programs\python\python312\lib\site-packages (0.14.6)
Requirement already satisfied: numpy<3,>=1.22.3 in c:\users\sudhir faujdar\appdata\local\programs\python\python312\lib\site-packages (from statsmodels) (2.3.1)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in c:\users\sudhir faujdar\appdata\local\programs\python\python312\lib\site-packages (from statsmodels) (1.16.0)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in c:\users\sudhir faujdar\appdata\local\programs\python\python312\lib\site-packages (from statsmodels) (2.3.1)
Requirement already satisfied: patsy>=0.5.6 in c:\users\sudhir faujdar\appdata\local\programs\python\python312\lib\site-packages (from statsmodels) (1.0.2)
Requirement already satisfied: packaging>=21.3 in c:\users\sudhir faujdar\appdata\local\programs\python\python312\lib\site-packages (from statsmodels) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sudhir faujdar\appdata\local\programs\python\python312\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sudhir faujdar\appdata\local\programs\python\python312\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sudhir faujdar\appdata\local\programs\python\python312\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\sudhir faujdar\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
fig = px.scatter(df, x='Price',
                 y='Revenue generated',
                 color='Product type',
                 hover_data = ['Number of products sold'],
                 trendline ="ols")
fig.show()

thus the company derives more revenue from skin care products, and the hiegher the price of skincare products, the more revenue the generate. Now lets have a look at the sales by product type:

sales data vs product sales :

In [8]:
Sales_data = df.groupby('Product type')['Number of products sold'].sum().reset_index()
# sales_data

pie_chart = px.pie(Sales_data, values = 'Number of products sold',
                   names = 'Product type',
                   title = 'Sales by product type',
                   hover_data = ['Number of products sold'],
                   hole = 0.5,
                   color_discrete_sequence = px.colors.qualitative.Pastel)
pie_chart.update_traces(textposition = 'inside', textinfo = 'percent+label')
pie_chart.show()

So 45% of the business comes from skincare products, 29.5% from haircaree, and 25.5% from cosmetics. now let have a look at the total revenue generated from shipping careers:

In [9]:
total_revenue = df.groupby('Shipping carriers')['Revenue generated'].sum().reset_index()
fig = go.Figure()
fig.add_trace(go.Bar(x=total_revenue['Shipping carriers'],
                      y=total_revenue['Revenue generated']))
fig.update_layout(title='Total Revenue by Shipping Carriers',
                  xaxis_title='Shipping Carriers',  
                  yaxis_title='Total Revenue')
fig.show()

In [10]:
df.describe()

,Price,Availability,Number of products sold,Revenue generated,Stock levels,Lead times,Order quantities,Shipping times,Shipping costs,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Defect rates,Costs
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000
mean,49.462461,48.400000,460.990000,5776.048187,47.770000,15.960000,49.220000,5.750000,5.548149,17.080000,567.840000,14.77000,47.266693,2.277158,529.245782
std,31.168193,30.743317,303.780074,2732.841744,31.369372,8.785801,26.784429,2.724283,2.651376,8.846251,263.046861,8.91243,28.982841,1.461366,258.301696
min,1.699976,1.000000,8.000000,1061.618523,0.000000,1.000000,1.000000,1.000000,1.013487,1.000000,104.000000,1.00000,1.085069,0.018608,103.916248
25%,19.597823,22.750000,184.250000,2812.847151,16.750000,8.000000,26.000000,3.750000,3.540248,10.000000,352.000000,7.00000,22.983299,1.009650,318.778455
50%,51.239830,43.500000,392.500000,6006.352023,47.500000,17.000000,52.000000,6.000000,5.320534,18.000000,568.500000,14.00000,45.905622,2.141863,520.430444
75%,77.198228,75.000000,704.250000,8253.976920,73.000000,24.000000,71.250000,8.000000,7.601695,25.000000,797.000000,23.00000,68.621026,3.563995,763.078231
max,99.171329,100.000000,996.000000,9866.465458,100.000000,30.000000,96.000000,10.000000,9.929816,30.000000,985.000000,30.00000,99.466109,4.939255,997.413450

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Product type             100 non-null    object
 1   SKU                      100 non-null    object
 2   Price                    100 non-null    float64
 3   Availability             100 non-null    int64
 4   Number of products sold  100 non-null    int64
 5   Revenue generated        100 non-null    float64
 6   Customer demographics    100 non-null    object
 7   Stock levels             100 non-null    int64
 8   Lead times               100 non-null    int64
 9   Order quantities         100 non-null    int64
 10  Shipping times           100 non-null    int64
 11  Shipping carriers        100 non-null    object
 12  Shipping costs           100 non-null    float64
 13  Supplier name            100 non-null    object
 14  Location                 100 non-null    object
 15  Lead time                100 non-null    int64
 16  Production volumes       100 non-null    int64
 17  Manufacturing lead time  100 non-null    int64
 18  Manufacturing costs      100 non-null    float64
 19  Inspection results       100 non-null    object
 20  Defect rates             100 non-null    float64
 21  Transportation modes     100 non-null    object
 22  Routes                   100 non-null    object
 23  Costs                    100 non-null    float64
dtypes: float64(6), int64(9), object(9)
memory usage: 18.9+ KB

In [12]:
Defect_data = df.groupby('Product type')['Defect rates'].sum().reset_index()
# sales_data

pie_chart = px.pie(Defect_data, values = 'Defect rates',
                   names = 'Product type',
                   title = 'total Defect Rates by Product Type',
                   hover_data = ['Defect rates'],
                   hole = 0.5,
                   color_discrete_sequence = px.colors.qualitative.Pastel)
pie_chart.update_traces(textposition = 'inside', textinfo = 'percent+label')
pie_chart.show()

In [15]:
Defect_data = df.groupby('Product type')['Defect rates'].mean().reset_index()
# sales_data

pie_chart = px.pie(Defect_data, values = 'Defect rates',
                   names = 'Product type',
                   title = 'Average Defect Rates by Product Type',
                   hover_data = ['Defect rates'],
                   hole = 0.5,
                   color_discrete_sequence = px.colors.qualitative.Pastel)
pie_chart.update_traces(textposition = 'inside', textinfo = 'percent+label')
pie_chart.show()

In [13]:
df.describe()

,Price,Availability,Number of products sold,Revenue generated,Stock levels,Lead times,Order quantities,Shipping times,Shipping costs,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Defect rates,Costs
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000
mean,49.462461,48.400000,460.990000,5776.048187,47.770000,15.960000,49.220000,5.750000,5.548149,17.080000,567.840000,14.77000,47.266693,2.277158,529.245782
std,31.168193,30.743317,303.780074,2732.841744,31.369372,8.785801,26.784429,2.724283,2.651376,8.846251,263.046861,8.91243,28.982841,1.461366,258.301696
min,1.699976,1.000000,8.000000,1061.618523,0.000000,1.000000,1.000000,1.000000,1.013487,1.000000,104.000000,1.00000,1.085069,0.018608,103.916248
25%,19.597823,22.750000,184.250000,2812.847151,16.750000,8.000000,26.000000,3.750000,3.540248,10.000000,352.000000,7.00000,22.983299,1.009650,318.778455
50%,51.239830,43.500000,392.500000,6006.352023,47.500000,17.000000,52.000000,6.000000,5.320534,18.000000,568.500000,14.00000,45.905622,2.141863,520.430444
75%,77.198228,75.000000,704.250000,8253.976920,73.000000,24.000000,71.250000,8.000000,7.601695,25.000000,797.000000,23.00000,68.621026,3.563995,763.078231
max,99.171329,100.000000,996.000000,9866.465458,100.000000,30.000000,96.000000,10.000000,9.929816,30.000000,985.000000,30.00000,99.466109,4.939255,997.413450

In [ ]:
# Average lead time and avg manufacturing cost

So the comapany is using three carriers for transportation, and Carrier B helps the company in generating more revenue. Now lets have a look at the average lead time and Average Manufacturing Cost for all products of the company:

In [14]:
avg_lead_time = df.groupby('Product type')['Lead time'].mean().reset_index()

In [15]:
avg_lead_time

  Product type  Lead time
0    cosmetics  13.538462
1     haircare  18.705882
2     skincare  18.000000

In [20]:
avg_manufacturing_costs = df.groupby('Product type')['Manufacturing costs'].mean().reset_index()

In [21]:
avg_manufacturing_costs

  Product type  Manufacturing costs
0    cosmetics            43.052740
1     haircare            48.457993
2     skincare            48.993157

In [22]:
result = pd.merge(avg_lead_time, avg_manufacturing_costs,
                  on='Product type',)
result.rename(columns={'Lead time': 'Average Lead Time',
                    'Manufacturing costs': 'Average Manufacturing Costs'},
                    inplace=True)
print(result)

  Product type  Average Lead Time  Average Manufacturing Costs
0    cosmetics          13.538462                    43.052740
1     haircare          18.705882                    48.457993
2     skincare          18.000000                    48.993157

#Analysing SKU ::
A Stock Keeping Unit (SKU, pronounced "skew") is a unique alphanumeric code assigned to products by retailers to track inventory internally. Ranging from 8-12 characters, SKUs distinguish product variations like size, color, or style, aiding in sales tracking and order accuracy.

In [24]:
revenue_chart = px.line(df, x = 'SKU',
                        y = 'Revenue generated',
                        title = 'Revenue generated by SKU')
revenue_chart.show()

There is another column in the dataset as stock levels. Stocks level refer to the number of the product of a store or business has in its inventery now let have a look at the stock of each SKU:

In [25]:
stock_chart = px.line(df, x  = 'SKU',
                      y = 'Stock levels',
                      title = 'Stock levels by SKU')
stock_chart.show()

Now lets have a look at the order quantity of each SKU:

In [26]:
order_quantity_chart = px.bar(df, x = 'SKU',
                              y = 'Order quantities',
                              title = 'Order Quantity by SKU')
order_quantity_chart.show()

cost analysis :-
Now lets analyse the shiping cost of Carriers:

In [28]:
shipping_cost_chart = px.bar(df, x = 'Shipping carriers',
                            y = 'Shipping costs',
                            title = 'Shipping Costs by Carriers')
shipping_cost_chart.show()

In [29]:
df.columns

Index(['Product type', 'SKU', 'Price', 'Availability',
       'Number of products sold', 'Revenue generated', 'Customer demographics',
       'Stock levels', 'Lead times', 'Order quantities', 'Shipping times',
       'Shipping carriers', 'Shipping costs', 'Supplier name', 'Location',
       'Lead time', 'Production volumes', 'Manufacturing lead time',
       'Manufacturing costs', 'Inspection results', 'Defect rates',
       'Transportation modes', 'Routes', 'Costs'],
      dtype='object')

In [39]:
Transportation_data = df.groupby('Transportation modes')['Costs'].mean().reset_index()

In [40]:
Transportation_data

  Transportation modes       Costs
0                  Air  561.712596
1                 Rail  541.747556
2                 Road  553.385988
3                  Sea  417.819148

In [43]:
pie_chart = px.pie(Transportation_data, values = 'Costs',
                   names = 'Transportation modes',
                   title = 'Cost distribution by Transportation modes',
                   hover_data = ['Costs'],
                   hole = 0.5,
                   color_discrete_sequence = px.colors.qualitative.Pastel)
pie_chart.update_traces(textposition = 'inside')
pie_chart.show()