In [1]:
import mysql.connector
import pandas as pd 

conn = mysql.connector.connect(
    host = "localhost",
    user = "root",
    password = "123@Faujdar",
    database = "CHURNMODELLING"
)

query = "select * from churn_modelling"
df = pd.read_sql(query,conn)
df.head()

C:\Users\SUDHIR FAUJDAR\AppData\Local\Temp\ipykernel_296\1910287133.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query,conn)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [8]:
df = df.drop(columns = 'Surname')

In [9]:
df.head()

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [10]:
df.isnull().sum()

RowNumber          0
CustomerId         0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [11]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [12]:
df.head(2)

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0

In [13]:
# encoding using label encoder
from sklearn.preprocessing import LabelEncoder

In [14]:
lb = LabelEncoder()

In [15]:
df['Geography'] = lb.fit_transform(df['Geography'])
df['Gender'] = lb.fit_transform(df['Gender'])

In [16]:
df.head()

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,0,0,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,2,0,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,0,0,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,0,0,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,2,0,43,2,125510.82,1,1,1,79084.10,0

In [17]:
x = df.drop(columns = 'Geography')
y = df['Geography']

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [21]:
import numpy as np

In [22]:
np.round(x_train.describe(),2)

,RowNumber,CustomerId,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00
mean,5012.51,15690665.10,651.65,0.55,38.90,5.00,76102.14,1.53,0.70,0.51,100431.29,0.21
std,2887.65,71847.43,96.37,0.50,10.52,2.88,62461.01,0.58,0.46,0.50,57518.92,0.40
min,2.00,15565701.00,350.00,0.00,18.00,0.00,0.00,1.00,0.00,0.00,90.07,0.00
25%,2512.75,15628215.50,585.00,0.00,32.00,3.00,0.00,1.00,0.00,0.00,51364.12,0.00
50%,5014.50,15690738.00,653.00,1.00,37.00,5.00,96447.52,1.00,1.00,1.00,100487.72,0.00
75%,7505.25,15753164.25,719.00,1.00,44.00,7.00,127611.33,2.00,1.00,1.00,149595.84,0.00
max,10000.00,15815660.00,850.00,1.00,92.00,10.00,250898.09,4.00,1.00,1.00,199970.74,1.00

In [23]:
# standardization
from sklearn.preprocessing import StandardScaler

In [24]:
stds = StandardScaler()

In [26]:
x_train_s = stds.fit_transform(x_train)
x_train_new = pd.DataFrame(x_train_s,columns = x_train.columns)

In [27]:
np.round(x_train_new.describe(),2)

,RowNumber,CustomerId,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00
mean,-0.00,0.00,0.00,0.00,-0.00,0.00,-0.00,0.00,-0.00,-0.00,0.00,0.00
std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
min,-1.74,-1.74,-3.13,-1.09,-1.99,-1.74,-1.22,-0.92,-1.54,-1.03,-1.74,-0.51
25%,-0.87,-0.87,-0.69,-1.09,-0.66,-0.70,-1.22,-0.92,-1.54,-1.03,-0.85,-0.51
50%,0.00,0.00,0.01,0.91,-0.18,-0.00,0.33,-0.92,0.65,0.97,0.00,-0.51
75%,0.86,0.87,0.70,0.91,0.49,0.69,0.82,0.81,0.65,0.97,0.85,-0.51
max,1.73,1.74,2.06,0.91,5.05,1.73,2.80,4.26,0.65,0.97,1.73,1.97