In [1]:
import pandas as pd
import numpy as np
import mysql.connector

In [2]:
conn = mysql.connector.connect(
    host = "localhost",
    user = "root",
    password = "123@Faujdar",
    database = "COVID"
)

In [3]:
query = "select * from covid_toy"

In [4]:
df = pd.read_sql(query,conn)
df.head()

C:\Users\SUDHIR FAUJDAR\AppData\Local\Temp\ipykernel_11288\2610741577.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query,conn)

   age  gender  fever cough     city has_covid
0   60    Male    103  Mild  Kolkata        No
1   27    Male    100  Mild    Delhi       Yes
2   42    Male    101  Mild    Delhi        No
3   31  Female     98  Mild  Kolkata        No
4   65  Female    101  Mild   Mumbai        No

In [8]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male    103  Mild  Kolkata        No
1   27    Male    100  Mild    Delhi       Yes
2   42    Male    101  Mild    Delhi        No
3   31  Female     98  Mild  Kolkata        No
4   65  Female    101  Mild   Mumbai        No

In [5]:
# labelencoding
from sklearn.preprocessing import LabelEncoder

In [6]:
lb = LabelEncoder()

In [9]:
df['gender'] = lb.fit_transform(df['gender'])
df['city'] = lb.fit_transform(df['city'])
df['cough'] = lb.fit_transform(df['cough'])

In [17]:
x = df.drop(columns = 'has_covid')
y = df['has_covid']

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [19]:
from sklearn.preprocessing import MinMaxScaler

In [20]:
mn = MinMaxScaler()

In [21]:
x_train_m = mn.fit_transform(x_train)

In [22]:
x_train_new = pd.DataFrame(x_train_m, columns = x_train.columns)

In [23]:
np.round(x_train_new.describe(),2)

         age  gender  fever  cough   city
count  72.00   72.00  72.00  72.00  72.00
mean    0.49    0.36   0.46   0.35   0.42
std     0.32    0.48   0.35   0.48   0.35
min     0.00    0.00   0.00   0.00   0.00
25%     0.19    0.00   0.17   0.00   0.00
50%     0.54    0.00   0.50   0.00   0.33
75%     0.77    1.00   0.71   1.00   0.67
max     1.00    1.00   1.00   1.00   1.00