In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder 

from sklearn.preprocessing import OrdinalEncoder

In [2]:
df = pd.read_csv('../files/tips - tips.csv')

In [3]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [5]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [7]:
x = df.drop(columns = ['smoker'])
y = df['smoker']

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 42)

In [10]:
x_train

     total_bill   tip     sex   day    time  size
228       13.28  2.72    Male   Sat  Dinner     2
208       24.27  2.03    Male   Sat  Dinner     2
96        27.28  4.00    Male   Fri  Dinner     2
167       31.71  4.50    Male   Sun  Dinner     4
84        15.98  2.03    Male  Thur   Lunch     2
..          ...   ...     ...   ...     ...   ...
106       20.49  4.06    Male   Sat  Dinner     2
14        14.83  3.02  Female   Sun  Dinner     2
92         5.75  1.00  Female   Fri  Dinner     2
179       34.63  3.55    Male   Sun  Dinner     2
102       44.30  2.50  Female   Sat  Dinner     3

[195 rows x 6 columns]

In [33]:
df = df.drop(columns = ['size'])

In [34]:
# simpleimputer for numerical data 
si = SimpleImputer(strategy = 'mean')
x_train_tip = si.fit_transform(x_train[['tip']]) 
x_test_tip = si.transform(x_test[['tip']])
x_train_tip.shape

(195, 1)

In [35]:
#ordinal encoding for categorical data
oe = OrdinalEncoder(categories=[['Male' , 'Female']])
x_train_sex = oe.fit_transform(x_train[['sex']])
x_test_sex = oe.transform(x_test[['sex']])
x_train_sex.shape

(195, 1)

In [36]:
#onehotencoder because day and time has morethen two subcategories
ohe = OneHotEncoder(drop = 'first', sparse_output=False)
x_train_daytime = ohe.fit_transform(x_train[['day', 'time']])
x_test_daytime = ohe.fit_transform(x_test[['day', 'time']])
x_train_daytime.shape

(195, 4)

In [37]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time'], dtype='object')

In [46]:
x_train_total_bill = x_train.drop(columns = ['tip', 'sex', 'day', 'time']).values

x_test_total_bill = x_test.drop(columns = ['tip', 'sex', 'day', 'time']).values

In [47]:
x_train_total_bill.shape

(195, 2)

In [48]:
x_train_transformed = np.concatenate((x_train_total_bill,x_train_tip, x_train_sex,
                                     x_train_daytime), axis = 1)

In [49]:
x_train_transformed.shape

(195, 8)

In [50]:
# columntransformer

In [51]:
from sklearn.compose import ColumnTransformer

In [52]:
transformer = ColumnTransformer(transformers = [
    ('tnf1', SimpleImputer(), ['tip']),
    ('tnf2', OrdinalEncoder(categories= [['Male' , 'Female']]),['sex']),
    ('tnf3',  OneHotEncoder(sparse_output = False , drop = 'first'),['day', 'time'])
],remainder = 'passthrough')

In [45]:
transformer.fit_transform(x_train).shape

(195, 8)

In [53]:
# -- OneHotEncoder
# -- getdummies

In [54]:
df = pd.read_csv('../files/tips - tips.csv')

In [55]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [58]:
# getdummies
a = pd.get_dummies(df, columns = ['sex','smoker','day','time'], drop_first=True)

In [59]:
a = a.astype(int)

In [60]:
a.head()

,total_bill,tip,size,sex_Male,smoker_Yes,day_Sat,day_Sun,day_Thur,time_Lunch
0,16,1,2,0,0,0,1,0,0
1,10,1,3,1,0,0,1,0,0
2,21,3,3,1,0,0,1,0,0
3,23,3,2,1,0,0,1,0,0
4,24,3,4,0,0,0,1,0,0

In [61]:
#onehotencoder
from sklearn.preprocessing import OneHotEncoder

In [62]:
df.head(2)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [64]:
ohe = OneHotEncoder(drop='first', sparse_output=False, dtype=np.int32)
ohe.fit_transform(df[['sex','smoker','day','time']])

array([[0, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 0],
       ...,
       [1, 1, 1, 0, 0, 0],
       [1, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0]], shape=(244, 6), dtype=int32)